# Generated by Django 4.2.4 on 2023-09-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(default='', max_length=50)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
    ]
