# Generated by Django 4.2.4 on 2023-09-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
