# Generated by Django 4.2.4 on 2023-09-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orders_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
